spring:
  application:
    name: pedidos-api

  datasource:
    url: jdbc:postgresql://localhost:5432/pedidosdb
    username: pedidos
    password: pedidos123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10        # máximo de conexões no pool
      minimum-idle: 5              # mínimo de conexões ociosas
      connection-timeout: 30000    # timeout para pegar uma conexão (ms)

  jpa:
    hibernate:
      ddl-auto: update           # Flyway cria o schema — Hibernate só valida
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true      # cria baseline se banco já existir
    baseline-version: 0            # ← versão de baseline

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

security:
  jwt:
    secret: "3cTvk9LmNpQrWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrSt"
    expiration: 86400000

server:
  port: 8081

logging:
  level:
    com.flaviorosa.pedidos_api: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO